name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main  # Change this if your default branch is different
  workflow_dispatch:  # Allows manual trigger from GitHub Actions UI

permissions:
  contents: write  # Required to push to gh-pages branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Export static files
        run: npm run export

      - name: Setup GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: out  # 'out' is the default export folder for static Next.js sites

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4